In [2]:
import pandas as pd

In [6]:
df = pd.read_csv('LT.csv')
df

,date,home_team,away_team,home_score,away_score,tourniment,city,country
0,1979-07-20,Kyrgyzstan,Lithuania,0,0,Friendly,Moscow,Soviet Union
1,1979-07-22,Georgia,Lithuania,5,0,Friendly,Moscow,Soviet Union
2,1979-07-24,Azerbaijan,Lithuania,0,1,Friendly,Moscow,Soviet Union
3,1979-07-28,Lithuania,Ukraine,0,2,Friendly,Moscow,Soviet Union
4,1979-07-30,Russia,Lithuania,2,0,Friendly,Moscow,Soviet Union
...,...,...,...,...,...,...,...,...
362,2019-09-10,Lithuania,Portugal,1,5,UEFA Euro qualification,Vilnius,Lithuania
363,2019-10-11,Ukraine,Lithuania,2,0,UEFA Euro qualification,Kharkiv,Ukraine
364,2019-10-11,Ukraine,Lithuania,2,0,UEFA Euro qualification,Kharkiv,Ukraine
365,2019-10-14,Lithuania,Serbia,1,2,UEFA Euro qualification,Vilnius,Lithuania
366,2019-10-14,Lithuania,Serbia,1,2,UEFA Euro qualification,Vilnius,Lithuania

In [8]:
df['Total'] = df['home_score'] + df['away_score']
df

,date,home_team,away_team,home_score,away_score,tourniment,city,country,Total
0,1979-07-20,Kyrgyzstan,Lithuania,0,0,Friendly,Moscow,Soviet Union,0
1,1979-07-22,Georgia,Lithuania,5,0,Friendly,Moscow,Soviet Union,5
2,1979-07-24,Azerbaijan,Lithuania,0,1,Friendly,Moscow,Soviet Union,1
3,1979-07-28,Lithuania,Ukraine,0,2,Friendly,Moscow,Soviet Union,2
4,1979-07-30,Russia,Lithuania,2,0,Friendly,Moscow,Soviet Union,2
...,...,...,...,...,...,...,...,...,...
362,2019-09-10,Lithuania,Portugal,1,5,UEFA Euro qualification,Vilnius,Lithuania,6
363,2019-10-11,Ukraine,Lithuania,2,0,UEFA Euro qualification,Kharkiv,Ukraine,2
364,2019-10-11,Ukraine,Lithuania,2,0,UEFA Euro qualification,Kharkiv,Ukraine,2
365,2019-10-14,Lithuania,Serbia,1,2,UEFA Euro qualification,Vilnius,Lithuania,3
366,2019-10-14,Lithuania,Serbia,1,2,UEFA Euro qualification,Vilnius,Lithuania,3

In [9]:
df['difference'] = df['home_score'] - df['away_score']
df

,date,home_team,away_team,home_score,away_score,tourniment,city,country,Total,difference
0,1979-07-20,Kyrgyzstan,Lithuania,0,0,Friendly,Moscow,Soviet Union,0,0
1,1979-07-22,Georgia,Lithuania,5,0,Friendly,Moscow,Soviet Union,5,5
2,1979-07-24,Azerbaijan,Lithuania,0,1,Friendly,Moscow,Soviet Union,1,-1
3,1979-07-28,Lithuania,Ukraine,0,2,Friendly,Moscow,Soviet Union,2,-2
4,1979-07-30,Russia,Lithuania,2,0,Friendly,Moscow,Soviet Union,2,2
...,...,...,...,...,...,...,...,...,...,...
362,2019-09-10,Lithuania,Portugal,1,5,UEFA Euro qualification,Vilnius,Lithuania,6,-4
363,2019-10-11,Ukraine,Lithuania,2,0,UEFA Euro qualification,Kharkiv,Ukraine,2,2
364,2019-10-11,Ukraine,Lithuania,2,0,UEFA Euro qualification,Kharkiv,Ukraine,2,2
365,2019-10-14,Lithuania,Serbia,1,2,UEFA Euro qualification,Vilnius,Lithuania,3,-1
366,2019-10-14,Lithuania,Serbia,1,2,UEFA Euro qualification,Vilnius,Lithuania,3,-1

In [50]:
draw = df['home_score'] == df['away_score']
print((draw).sum())

73

In [97]:

Big_loss = df[(df['home_team'] == 'Lithuania') & (df['home_score'] > df['away_score'])]
Big_loss.difference.max()

KeyError: 1